### ISSUE TITLE
Soil data on GlobusOnline

### ISSUE THREAD

**Issue by jramarohetra** [RDCEP/psims#1]
Hello,
I tried to get the two available global datasets using Globus Online. I found the climate data but the /soils/ directory is empty. Where could I find these soil data ?
Thanks,
Johanna

**Comment by DavidMichaelKelly** [comment]
H Johanna,

Sorry about that - I needed to adjust the permissions after we moved some data around. Could you please give it another try?

Thanks,
David

**Comment by DavidMichaelKelly** [comment]
This soil dataset should be in davidk#psims, /soils/hwsd/hwsd200.wrld.30min

**Comment by jramarohetra** [comment]
Yes, got it !
Thanks !

**Comment by JJguri** [comment]
Hi @DavidKelly999, I was looking for the soil file and I could not find it at the described address (see attached). Could you please help me with that? Thanks
![Untitled](https://user-images.githubusercontent.com/41041705/98199366-b9476d00-1f76-11eb-8828-4309ac472108.jpg)

**Comment by DavidMichaelKelly** [comment]
Hey Jonathan. The soil data is split into 2x2 degree tiles. If you want the full global dataset, you can download the entire psims2 /data/soils/gsde/gsde.2deg.tile directory. If you just want a single tile, you can download the appropriate file in the gsde/gsde.2deg.tile/latidx/soil_latidx_lonidx.tile.nc4

**Comment by JJguri** [comment]
thanks, @DavidKelly999! I already downloaded the data.
