### ISSUE TITLE
The executable /scratch/midway/davidkelly999/psims-python/pysims/pysims.py does not exist

### ISSUE THREAD

**Issue by AHCG** [RDCEP/psims#10]
Hello all,

I may have found a minor bug. Even though I am running pSIMS with "-s local", I am getting the following error: 

Exception in pysims:
    Arguments: [--campaign, /ihome/jlopez/git/psims2/run003/campaign, --param, /ihome/jlopez/git/psims2/run003/params.psims, --tlatidx, 0024, --tlonidx, 0044, --slatidx, 1, --slonidx, 1, --split, 1, --rundir, /ihome/jlopez/git/psims2/run003]
    Host: local
    Directory: psims-all-20160720-1101-nynnne08/jobs/q/pysims-q0ccs4tm
        exception @ swift-int.k, line: 530
Caused by: The executable /scratch/midway/davidkelly999/psims-python/pysims/pysims.py does not exist
        exception @ swift-int.k, line: 512
Caused by: Job failed with and exit code of 254

I am attaching the whole output file to this message.

Best,

Jose

[test_psims.o872033.txt](https://github.com/RDCEP/psims/files/374007/test_psims.o872033.txt)

**Comment by DavidMichaelKelly** [comment]
Hi Jose,

The file conf/swift.properties has the path name to the executables, for both local execution and when running on a cluster. For local execution, you'll have to edit the lines that start with "app.local". Also in the local site definition, you'll have to edit the workDir and taskDir paths to point to the location of a scratch directory. I'll update the readme to mention this.

**Comment by DavidMichaelKelly** [comment]
I've made a change to make local execution easier. Now by default, the apps and work directory will be set via relative paths rather than absolute paths. This means that for new users it should work out of the box without having to make any modifications.

**Comment by AHCG** [comment]
Thanks David. I tried both ways and both work very well.
