### ISSUE TITLE
Error parsing arguments: Unknown option or flag: '-site'

### ISSUE THREAD

**Issue by xxjjyy69** [RDCEP/psims#11]
Hi all, 
    I have successfully simulated a single point and a full tile. However, when I run a single tile via swift I have encountered an ERROR.  
   The command is  ./psims -s local -p /home/joyxu/psims-release-2.0/joyrun/test1/params.dssat.sample -c /home/joyxu/psims-release-2.0/joyinput/campaign -t /home/joyxu/psims-release-2.0/joyinput/tilelists/tileList.1

And here is an ERROR.
Sites           = local
Parameter       = /home/joyxu/psims-release-2.0/joyrun/test1/params.dssat.sample
Tilelist        = /home/joyxu/psims-release-2.0/joyinput/tilelists/tileList.1
Campaign        = /home/joyxu/psims-release-2.0/joyinput/campaign
Split           = 1
Run directory   = /home/joyxu/psims-release-2.0/run004
Work directory  = /home/joyxu/psims-release-2.0/run004
Pcoasters       = false

Error parsing arguments: Unknown option or flag: '-site'

I'd appreciate if you could help.

**Comment by DavidMichaelKelly** [comment]
Hello,

Can you verify that the correct version of swift is in your path? You can do this by running 'which swift'. It should point to the swift 0.95 that you installed as part of this setup.

If you're on a mac, it could be pointing to apple's swift for ios programming. If this is the case, I'd change the PATH environment variable so the swift that psims uses is the first thing in your path, something like: export PATH=/path/to/swift/bin:$PATH

**Comment by xxjjyy69** [comment]
Thank you so much, the version swift 0.95 works.
