### ISSUE TITLE
All values of sample-output.nc4 are missing

### ISSUE THREAD

**Issue by xxjjyy69** [RDCEP/psims#13]
Hi,
 I run a single tile via Swift, using command ./psims -s "local" -p /home/joyxu/psims-release-2.0/joyrun/test1/params.dssat.sample -c /home/joyxu/psims-release-2.0/joyinput/campaign -t /home/joyxu/psims-release-2.0/joyinput/tilelists/tileList.1

However, the output sample-output.nc4 and output_00xx.psims.nc has not data inside. 
All value are missing and min and max both 0 for all variables.  No errors show during simulations and I have successfully run a single tile without Swift.  

The attachment is log file.

[logfile.zip](https://github.com/RDCEP/psims/files/1073890/logfile.zip)

**Comment by DavidMichaelKelly** [comment]
Hi there,

Null output can be created for various reasons. It happens any time a translator fails. This could be related to something in the simulation, like freezing crops, or it could be some type of misconfiguration. The best way to see what's happening is to run a single point simulation.  There's more information about this in step 1 of quickstart.txt. The printed output of the command there will be more useful for debugging, so you can see what's happening with each individual translator. Are any translators returning false? Are you seeing any error messages there?
