### ISSUE TITLE
About how to compile the pDSSAT and pAPSIM

### ISSUE THREAD

**Issue by RAN1222** [RDCEP/psims#16]
Hi,
I have downloaded APSIM7.9 and DSSAT4.6, but I have question about how to compile them, and produce an executable Apsim79-pysims.tar.gz and DSCSM046.EXE as the params.apsim.sample and params.dssat.sample files  need?

Best Wishes,
Ran

**Comment by DavidMichaelKelly** [comment]
Added notes about how to compile crop models to readme
