### ISSUE TITLE
An error when I compile Apsim

### ISSUE THREAD

**Issue by RAN1222** [RDCEP/psims#17]
Hi,

I have met a problem when I compile Apsim, the error was about ”/rz2417/Apsim79/Model/ProcessDataTypesInterface.exe ../DataTypes/Datatypes.xml TclComponent.macro
/rigel/cwc/users/rz2417/Apsim79/Model/ProcessDataTypesInterface.exe: /rigel/cwc/users/rz2417/Apsim79/Model/ProcessDataTypesInterface.exe: cannot execute binary file
make: *** [CIDataTypes.tcl] Error 126"

May I ask how to solve this?
Thanks,
Ran

**Comment by DavidMichaelKelly** [comment]
Can you please attach the full output? The makefiles should try to prepend a 'mono' command before running those type of executables.

**Comment by RAN1222** [comment]
[output.txt](https://github.com/RDCEP/psims/files/1624189/output.txt)
The output is attached. I have done as the introduction in the GitHub,
"Install Apsim
Checkout the source: svn co http://apsrunet.apsim.info/svn/apsim/tags/Apsim79
cd Apsim79
patch -p0 < /path_to_psims/models/papsim/papsim79.patch
cd model/Build
mcs VersionStamper.cs
mono VersionStamper.exe Directory=$PWD
./MakeAll.sh"
And add the bin directory and lib directory of mono and mono-basic, respectively. Thanks!
Best wishes,
Ran

**Comment by DavidMichaelKelly** [comment]
I see the message you're talking about, but make continues after that and successfully builds ComponentInterface2.so. Is Model/ApsimModel.exe being created?

**Comment by RAN1222** [comment]
Yes, ComponentInterface2.so is successfully built, But I cannot find Model/ApsimModel.exe, only Apsim.exe, ApsimToSim.exe, BundleApsim.exe, ConToSim.exe, CreatePatch.exe, cscs.exe, ProcessDataTypesInterface.exe be created in the Model directory.

**Comment by RAN1222** [comment]
Hi,

I still cannot find ApsimModel.exe, may I ask is there any alternative way to solve this problem?

Best wishes,
Ran

**Comment by DavidMichaelKelly** [comment]
Glad you were able to get past this compile issue. How were you able to resolve it?

**Comment by RAN1222** [comment]
**Dear David,


It seems MakeAll.sh doesn't build every APSIM module. And I do './RunMake.sh ../ApsimModel'  after './MakeAll.sh', then the ApsimModel.exe has been created. My MakeAll.sh is below,**

#! /bin/sh

cd ../..
export APSIM=`pwd`
cd $APSIM/Model/Build

ulimit -s unlimited
rm -f $APSIM/Model/Build/Build.out

if [ "$1" != "clean" ]; then
    mcs VersionStamper.cs
fi

# -------------------------------------------------------------
# This script compiles the APSIM engine and modules
# -------------------------------------------------------------

# -------------------------------------------------------------
# Need to process the datatypes.interface file and auto-
# generate the datatypes.cpp, .h etc.
# -------------------------------------------------------------
./MakeProject.sh CSGeneral $1
./MakeProject.sh CMPServices $1
./MakeProject.sh ApsimFile $1
./MakeProject.sh DataTypes $1

# -------------------------------------------------------------
# Need to compile all infrastructure projects before the main
# bulk of projects
# -------------------------------------------------------------
./MakeProject.sh General $1
./MakeProject.sh ApsimShared $1
./MakeProject.sh Protocol $1
./MakeProject.sh ComponentInterface $1
./MakeProject.sh ComponentInterface2 $1
./MakeProject.sh CSDotNetComponentInterface $1
./MakeProject.sh FortranInfrastructure $1
./MakeProject.sh FortranComponentInterface $1
./MakeProject.sh FortranComponentInterface2 $1
./MakeProject.sh ProtocolManager $1
./MakeProject.sh CropTemplate $1
./MakeProject.sh DotNetProxies $1
./MakeProject.sh ConToSim         $1
./MakeProject.sh ConToApsim       $1
./MakeProject.sh ApsimToSim       $1
./MakeProject.sh Apsim $1

# -------------------------------------------------------------
# Now we can compile all the rest of the APSIM projects.
# -------------------------------------------------------------
./MakeProject.sh Accum            $1
./MakeProject.sh AgPasture        $1
./MakeProject.sh Canopy           $1
./MakeProject.sh Clock            $1
./MakeProject.sh CropMod          $1
./MakeProject.sh Eo               $1
./MakeProject.sh Erosion          $1
./MakeProject.sh Fertiliser       $1
./MakeProject.sh Grasp            $1
./MakeProject.sh Graz             $1
./MakeProject.sh Growth           $1
./MakeProject.sh Input            $1
./MakeProject.sh Irrigation       $1
./MakeProject.sh Log              $1
./MakeProject.sh Maize            $1
./MakeProject.sh MaizeZ           $1
./MakeProject.sh Manager          $1
./MakeProject.sh Manager2         $1
./MakeProject.sh Map              $1
./MakeProject.sh MicroClimate     $1
./MakeProject.sh MicroMet         $1
./MakeProject.sh Millet           $1
./MakeProject.sh Operations       $1
./MakeProject.sh Oryza            $1
./MakeProject.sh Parasite         $1
./MakeProject.sh Pasture          $1
./MakeProject.sh PatchInput       $1
./MakeProject.sh Plant            $1
./MakeProject.sh Plant2           $1
./MakeProject.sh Pond             $1
./MakeProject.sh ProtocolManager  $1
./MakeProject.sh Report           $1
./MakeProject.sh Root             $1
./MakeProject.sh SiloInput        $1
./MakeProject.sh SOI              $1
./MakeProject.sh SoilErosion      $1
./MakeProject.sh SoilN            $1
./MakeProject.sh SoilNitrogen     $1
./MakeProject.sh SoilP            $1
./MakeProject.sh SoilTemp         $1
./MakeProject.sh SoilTemp2        $1
./MakeProject.sh SoilWat          $1
./MakeProject.sh SoilWater        $1
./MakeProject.sh Solute           $1
./MakeProject.sh Sorghum          $1
./MakeProject.sh Stock            $1
./MakeProject.sh Sugar            $1
./MakeProject.sh Supplement       $1
./MakeProject.sh Surface          $1
./MakeProject.sh SurfaceOM        $1
./MakeProject.sh SurfaceTemp      $1
./MakeProject.sh SWIM2            $1
./MakeProject.sh SWIM3            $1
./MakeProject.sh SysBal           $1
./MakeProject.sh TclLink          $1
./MakeProject.sh Tracker          $1
./MakeProject.sh Tree             $1
./MakeProject.sh UrinePatch       $1
./MakeProject.sh WaterSupply      $1
./MakeProject.sh YieldProphet     $1
./MakeProject.sh DDRules          $1
./MakeProject.sh FarmSimGraze     $1
./MakeProject.sh JobScheduler/CreatePatch      $1

**Best wishes,
Ran**
