### ISSUE TITLE
A problem when I test the pAPSIM model

### ISSUE THREAD

**Issue by RAN1222** [RDCEP/psims#18]
**Hi,
I have met a problem when I test the pAPSIM model according to the quickstart.txt.  The content of params.apsim.sample file was following,**

model:       apsim79
weather:     /rigel/cwc/users/rz2417/data/clim/agmerra.2deg.tile
soils:       /rigel/cwc/users/rz2417/data/soil/gsde/gsde.2deg.tile
refdata:     /rigel/cwc/users/rz2417/data/reference/refdata
out_file:    apsim.test
executable:  /rigel/cwc/users/rz2417/Apsim79/Model/ApsimModel.exe
outtypes:    .met,.apsim,.out,.json,.txt

ref_year:    1980
num_years:   31
scen_years:  31
scens: 2

delta:       "30,30"
tdelta:      "120,120"

num_lats:    360
num_lons:    720
lat_zero:    90
lon_zero:    -180
irr_flag:    true
irr_1st:     false

# Variables to extract
variables:   biomass,yield,planting_date,DaysAfterSowing,flowering_das,maturity_das,RainIn,Temp_year,TempIn,RadiationIn,IrrigationIn,WaterUse,actual_ET,FertiliserIn,NO3_leaching,N2Oemission_year,N2OemissionIn,CO2emission_year,CO2emissionIn
var_units:   "kg/ha,kg/ha,day,days,days,days,mm,oC,oC,MJ/m2,mm,mm,mm,kg/ha,kgN/ha,kgN2O/ha,kgN2O/ha,kgC/ha,kgC/ha"
long_names:  "biomass,yield,DateOfPlanting,DaysAfterSowing,flowering_das,maturity_das,RainIn,Temp_year,TempIn,RadiationIn,IrrigationIn,WaterUse,actual_ET,FertiliserIn,NO3_leaching,N2Oemission_year,N2OemissionIn,CO2emission_year,CO2emissionIn"

# Campaign translator
tappcmp:
   class:         camp2json
   campaignfile:  Campaign.nc4
   expfile:       exp_template.json
   outputfile:    experiment.json

# Input translator
tappinp:
    class:         apsim79.jsons2apsim
    soilfile:      soil.json
    soiltile:      1.soil.nc4
    expfile:       experiment.json
    templatefile:  template.apsim
    outputfile:    Generic.apsim

# Weather translator
tappwth:
   class:      apsim79.psims2met
   inputfile:  1.clim.nc4
   variables:  tasmin,tasmax,rsds,pr,wind
   outputfile: Generic.met

# Post processing translation
postprocess:
    class:     apsim79.out2psims
    inputfile: Generic.out

tapptilewth:
    class:     tile_translator

tapptilesoil:
    class:     tile_translator_soil

tappnooutput:
    class: nooutput2psims

**and the output would as following, however, apsim79 file existed in the dicrectory ‘psims/pysims/translators’**
[rz2417@holmes testapsim]$ /rigel/cwc/users/rz2417/psims/pysims/pysims.py --param /rigel/cwc/users/rz2417/psims/pysims/params.apsim.sample --campaign /rigel/cwc/users/rz2417/data/camp/campaign --tlatidx 0024 --tlonidx 0044 --latidx 0096 --lonidx 0173
Invalid tappinp translator specified. Valid translators are camp2json, apsim75.jsons2apsim, dssat45.out2psims, dssat.jsons2dssat, dssat46.out2psims, tile_translator, stage_inputs_sharedfs, dssat46.psims2wth, dssat46.jsons2dssat, dssat46.jsons2dssatlong, dssat.out2psims, noop, apsim75.out2psims, apsim75.psims2met, dssat.psims2wth, dssat45.jsons2dssatlong, dssat46.out2psimsdaily, nooutput2psimsdaily, nooutput2psims, dssat45.jsons2dssat, stage_outputs_sharedfs, dssat.jsons2dssatlong, tile_translator_soil, dssat.out2psimsdaily, dssat45.psims2wth

Traceback (most recent call last):
  File "/rigel/cwc/users/rz2417/psims/pysims/pysims.py", line 175, in <module>
    input_translator         = translator_factory_obj.create_translator(config, "tappinp")
  File "/rigel/cwc/users/rz2417/psims/pysims/translators/translator_factory.py", line 76, in create_translator
    t = self.translator_objects[config.get(translator_type)['class']](config, translator_type, **kwargs)
KeyError: 'apsim79.jsons2apsim'

Could you help me to solve this problem?

Best wishes,
Ran

**Comment by DavidMichaelKelly** [comment]
The apsim79 translators should be registered now. Can you please update and see if you're able to get further?

**Comment by RAN1222** [comment]
Dear David,

**Sorry for late reply, I update the psims, but there was a new problem as follows,**
[rz2417@watson testapsim]$ /rigel/cwc/users/rz2417/psims/pysims/pysims.py --param /rigel/cwc/users/rz2417/psims/pysims/params.apsim.sample --campaign /rigel/cwc/users/rz2417/data/camp/campaign --tlatidx 0024 --tlonidx 0044 --latidx 0096 --lonidx 0173
0024/0044, StageInputsSharedFS, run_tile, 0.680694, True
0096/0173, Noop, run, 0.000006, True
0096/0173, StageInputsSharedFS, run, 0.221856, True
0096/0173, SoilTileTranslator, run, 4.430474, True
0096/0173, TileTranslator, run, 4.406991, True
0096/0173, Noop, run, 0.000008, True
0096/0173, Camp2Json, run, 0.149317, True
0096/0173, Noop, run, 0.000007, True
0096/0173, Psims2Met, run, 1.067415, True
[jsons2apsim.pyc]: (0096/0173) Traceback (most recent call last):
  File "/rigel/cwc/users/rz2417/psims/pysims/translators/apsim79/jsons2apsim.py", line 404, in run
    s_tmp['cropName'] = exp_i['crop_name']
KeyError: 'crop_name'

0096/0173, Jsons2Apsim, run, 0.031856, False
0096/0173, NoOutput2Psims, run, 0.085792, True

**Could you help me find some solutions?**

**Best wishes,
Ran**

**Comment by DavidMichaelKelly** [comment]
Hi Ran,

I think that specific issue stems from running a dssat campaign file in an apsim simulation. You'll need to have apsim specific campaign files, reference data (with apsim 7.7 cultivars and templates), etc. If you don't have that data, let me know and I'll try to put something together for testing.

**Comment by JJguri** [comment]
> Hi Ran,
> 
> I think that specific issue stems from running a dssat campaign file in an apsim simulation. You'll need to have apsim specific campaign files, reference data (with apsim 7.7 cultivars and templates), etc. If you don't have that data, let me know and I'll try to put something together for testing.

Dear @DavidKelly999 , @RAN1222 could you please share the campaign file with the apsim format? Thanks
