### ISSUE TITLE
psims using DSSAT 4.7 or above

### ISSUE THREAD

**Issue by rubcalvo** [RDCEP/psims#29]
Dear all! I hope you are doing great! I was wondering if pSIMS could be used with newer versions of DSSAT, because it seems that DSSAT version 4.6 is no longer available in github. Thanks!

**Comment by DavidMichaelKelly** [comment]
Hey there! Unfortunately this repo is no longer being maintained due to funding. I have not tried running any version of dssat newer than 4.6. As long as the format of dssat inputs and outputs has not changed between versions, I'd guess it would work

**Comment by AnnaBlanke** [comment]
We were able to run pSIMS with DSSAT v 4.8 without making any changes to the pSIMS code, so yes, its possible. What a pity that pSIMS is no longer maintained. I found it very useful

**Comment by rubcalvo** [comment]
thank you @DavidKelly999 and @AnnaHampf for your replies! I'll try to run psims with DSSAT 4.8 then.
Thank you!
