### ISSUE TITLE
DSSAT soils to pSIMS soils

### ISSUE THREAD

**Issue by schmidtfederico** [RDCEP/psims#6]
Hi,

I've noticed that there's a script in the soil database hosted in Globus named `make_soils.sh` that uses another one called `SOL2json.py` that I couldn't inside the soil database directory.

I'm working with colleagues that are used to use DSSAT and ask me to recreate experiments they already did in the past with DSSAT in pSIMS, so they give me their soils in .SOL format.

Is there a chance you can share that `SOL2json.py` script or make it part of pSIMS so we can speed up that process?

Greetings,
Federico.

**Comment by jchryssanthacopoulos** [comment]
SOL2json.py should now be in the data/tapps directory.
