### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2713' 

### ISSUE THREAD

**Issue by AHCG** [RDCEP/psims#9]
Hello David,

Hope you are doing well. I am having trouble running pSIMS in a local cluster. I get the following error:

Traceback (most recent call last):
  File "/ihome/jlopez/git/psims2/pysims/sanity.py", line 109, in <module>
    assert_true(is_file('params', args.params))
  File "/ihome/jlopez/git/psims2/pysims/sanity.py", line 24, in assert_true
    print check + " " + passed[1]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2713' in position 5: ordinal not in range(128)

I'm running the following command:

./psims -s local -p path-to-file/params.dssat.sample.jose -c path-to-file/campaign -t path-to-file/example-tilelist

I am using python 2.7.11. I tried using a newer version of python (3.5) and got a different error. Any suggestions? 

Best,

Jose

**Comment by DavidMichaelKelly** [comment]
Hi Jose,

Before psims runs, a script called the sanity checker runs that does some basic checks on the params file. When a test passes it prints unicode checkmarks. On some configurations this might cause a problem, so I committed a change to remove them. Can you please update and give it another try? Thanks!

**Comment by AHCG** [comment]
Thanks David, problem solved!
